name: Alpha
on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set alpha version
        run: |
          git config --global user.email "chesney@nyffels.be"
          git config --global user.name "Chesney Nyffels"
          npm version prerelease
